# because we want to use OidcClientFilter
quarkus.openapi-generator.codegen.enable-security-generation = false

# /!\ BEWARE: dashes ("-") are replaced by underscores ("_") in `config-key` when generating the client
quarkus.openapi-generator.codegen.spec.my_service_json.config-key = patient_service
quarkus.openapi-generator.codegen.spec.my_service_json.additional-enum-type-unexpected-member = true
quarkus.openapi-generator.codegen.spec.my_service_json.base-package = my.client
quarkus.openapi-generator.codegen.spec.my_service_json.additional-api-type-annotations = @org.eclipse.microprofile.faulttolerance.Timeout(value = 10, unit = java.time.temporal.ChronoUnit.SECONDS);@org.eclipse.microprofile.faulttolerance.Retry(maxRetries = 1, delay = 1, delayUnit = java.time.temporal.ChronoUnit.SECONDS, abortOn = {org.jboss.resteasy.reactive.ClientWebApplicationException.class});@io.quarkus.oidc.client.filter.OidcClientFilter("${quarkus.openapi-generator.codegen.spec.patient_service_json.config-key}")
quarkus.openapi-generator.codegen.spec.my_service_json.additional-model-type-annotations = @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_EMPTY)
quarkus.openapi-generator.codegen.spec.my_service_json.type-mappings.DateTime=LocalDateTime
quarkus.openapi-generator.codegen.spec.my_service_json.import-mappings.LocalDateTime=java.time.LocalDateTime
quarkus.openapi-generator.codegen.spec.my_service_json.type-mappings.Date=LocalDate
quarkus.openapi-generator.codegen.spec.my_service_json.import-mappings.LocalDate=java.time.LocalDate
quarkus.openapi-generator.codegen.spec.my_service_json.mutiny=true
